ruby '2.7.1'
source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'rest-client'
gem 'minecraft-query', require: 'rcon/rcon'
gem 'dnsimple'
gem 'activesupport'
gem 'droplet_kit'
gem 'net-ssh'
gem 'json', '>= 1.8.5'
