ruby '2.0.0'
source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'rest-client'
gem 'minecraft-query', require: 'rcon/rcon'
gem 'dnsimple'
gem 'activesupport', require: 'active_support/core_ext'
gem 'droplet_kit'
gem 'net-ssh'
